# logger
logging.level.app.nottobe: DEBUG
logging.file: logs/nottobe.log

server.port: 80
spring.mvc.favicon.enabled: false

#thymeleaf start
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false
#thymeleaf end

# database
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://rm-2ze970347k5e98h0uqo.mysql.rds.aliyuncs.com:3306/npyq?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true
spring.datasource.username: mantester
spring.datasource.password: mantester 
spring.datasource.tomcat.initSQL: "SET NAMES 'utf8mb4'"
spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring.jpa.properties.hibernate.show_sql: true

# redis
spring.redis.host: r-2ze5e06cd829b4f4.redis.rds.aliyuncs.com
spring.redis.port: 6379
spring.redis.password: Manlanredis2017
spring.redis.database: 0

# session
session.expire.days: 30

# aliyun oss
oss.endpoint: oss-cn-beijing.aliyuncs.com
oss.host: http://s.manlanvideo.com
oss.bucketName: manlan
