# logger
logging.level.app.nottobe: DEBUG
logging.file: logs/nottobe.log

server.host: ntb.xxicp.cn
server.port: 7000
spring.mvc.favicon.enabled: false

web.static-location: /data/static/
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: 
      - classpath:/static/
      - classpath:/public/
      - classpath:/resources/
      - classpath:/META-INF/resources/
      - file:${web.static-location}

#thymeleaf start
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false
#thymeleaf end

# database
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://106.12.207.243:3306/npyq?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
spring.datasource.username: root
spring.datasource.password: Abc1234567!
spring.datasource.tomcat.initSQL: "SET NAMES 'utf8mb4'"
spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring.jpa.properties.hibernate.show_sql: true

# redis
spring.redis.host: 106.12.207.243
spring.redis.port: 6379
spring.redis.password: 

# session
session.expire.days: 30
